apiVersion: apps/v1
kind: Deployment
#Deployment mongodb-deployment is created
metadata:
  name: deploy-mongodb
  labels:
    app: mongodb
#Deployment creates one replicated Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: datahost
          hostPath:
                  path: '/data/db'
      containers:
        - name: mongodb
          image: 'mongodb:v1'
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: '/data/db'
              name: datahost
